name: Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build an Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        run: |
          ls
        env:
          CI: true